#!/usr/bin/env python3
"""Generate a markdown metrics report from the training summary.

Usage:
    python scripts/report_metrics.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from src.config import MODELS_DIR, REPORTS_DIR, ensure_project_directories  # noqa: E402

SUMMARY_PATH = REPORTS_DIR / "metrics" / "training_summary.json"
CLASSIFIER_PATH = REPORTS_DIR / "metrics" / "classifier.json"
OUTPUT_PATH = REPORTS_DIR / "metrics_summary.md"

_TICK = "✅"
_CROSS = "❌"


def _badge(ok: bool) -> str:
    return _TICK if ok else _CROSS


def main() -> None:
    ensure_project_directories()
    if not SUMMARY_PATH.exists():
        raise SystemExit(f"Run `python train_all.py` first. Missing: {SUMMARY_PATH}")

    summary = json.loads(SUMMARY_PATH.read_text(encoding="utf-8"))
    classifier_metrics = (
        json.loads(CLASSIFIER_PATH.read_text(encoding="utf-8"))
        if CLASSIFIER_PATH.exists()
        else {}
    )

    # ── Classifier ────────────────────────────────────────────────────────
    clf = summary.get("classifier", {})
    rec = summary.get("recommender", {})
    clu = summary.get("clustering", {})
    fit = summary.get("fit_predictor", {})

    lines = [
        "# SmartHire — Training Metrics Summary",
        "",
        "> Auto-generated by `scripts/report_metrics.py` — do not edit manually.",
        "",
        "## Artifact Status",
        "",
        "| Artifact | File | Status |",
        "|----------|------|--------|",
    ]
    artifacts = [
        ("Resume Classifier", "resume_classifier.joblib"),
        ("Job Recommender", "recommender.joblib"),
        ("Role Clustering", "clustering.joblib"),
        ("Fit Predictor", "fit_predictor.joblib"),
    ]
    for name, fname in artifacts:
        exists = (MODELS_DIR / fname).exists()
        lines.append(f"| {name} | `{fname}` | {_badge(exists)} |")

    lines += [
        "",
        "---",
        "",
        "## Classifier",
        "",
        f"- **Selected model**: `{clf.get('selected_model', 'N/A')}`",
        f"- **Training rows**: {clf.get('training_rows', 'N/A')}",
        f"- **Validation accuracy**: {clf.get('validation_accuracy', 0):.3f}",
        f"- **Validation weighted F1**: {clf.get('validation_weighted_f1', 0):.3f}",
        "",
        "### Candidate comparison",
        "",
        "| Model | Weighted F1 |",
        "|-------|-------------|",
    ]
    for model_name, score in (clf.get("candidate_weighted_f1") or {}).items():
        selected_marker = " ← selected" if model_name == clf.get("selected_model") else ""
        lines.append(f"| `{model_name}` | {score:.3f}{selected_marker} |")

    lines += [
        "",
        "---",
        "",
        "## Recommender",
        "",
        f"- **Job count**: {rec.get('job_count', 'N/A')}",
        f"- **Vocabulary size**: {rec.get('vocabulary_size', 'N/A')}",
        "",
        "---",
        "",
        "## Clustering",
        "",
        f"- **Selected clusters**: {clu.get('selected_clusters', 'N/A')}",
        "",
        "### Candidate evaluation",
        "",
        "| k | Silhouette | Inertia |",
        "|---|-----------|---------|",
    ]
    for row in clu.get("candidates") or []:
        marker = " ← selected" if row["n_clusters"] == clu.get("selected_clusters") else ""
        lines.append(
            f"| {row['n_clusters']} | {row['silhouette']:.4f}{marker} | {row['inertia']:.1f} |"
        )

    lines += [
        "",
        "---",
        "",
        "## Fit Predictor",
        "",
        f"- **Synthetic pair count**: {fit.get('synthetic_pair_count', 'N/A')}",
        f"- **Validation accuracy**: {fit.get('validation_accuracy', 0):.3f}",
        f"- **Note**: {fit.get('note', '')}",
        "",
    ]

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Report written to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
